"""Render a composed document plan (title + sections of typed blocks) to
Markdown, DOCX, and PDF. Pure rendering, no LLM calls -- placement was already
decided by compose.py; this just draws it.
"""

import shutil
from pathlib import Path
from xml.sax.saxutils import escape

from PIL import Image as PILImage


def _caption(block: dict, meta: dict) -> str:
    # compose.py's LLM sometimes leaves an image/table block's caption empty
    # despite the placement decision -- fall back to the classify-step caption,
    # which always exists, rather than rendering an empty caption.
    return block.get("caption") or meta.get("caption", "")


def render_table_markdown(table: dict, caption: str = "") -> str:
    """Renders one table's headers/rows (+ optional caption) as a standalone
    markdown table. Shared by render_markdown's per-block rendering and
    routes/review.py's single-table export, so there's exactly one place that
    knows how a table becomes markdown."""
    lines = ["| " + " | ".join(table["headers"]) + " |"]
    lines.append("| " + " | ".join("---" for _ in table["headers"]) + " |")
    for row in table["rows"]:
        lines.append("| " + " | ".join(str(c) for c in row) + " |")
    if caption:
        lines.append("")
        lines.append(f"*{caption}*")
    return "\n".join(lines)


def render_markdown(title: str, sections: list[dict], images_by_id: dict, tables_by_id: dict, output_dir: Path) -> Path:
    images_dir = output_dir / "images"
    images_dir.mkdir(parents=True, exist_ok=True)

    lines = [f"# {title}", ""]
    for section in sections:
        lines.append(f"## {section['heading']}")
        lines.append("")
        for block in section["blocks"]:
            if block["type"] == "paragraph":
                if block["text"]:
                    lines.append(block["text"])
                    lines.append("")
            elif block["type"] == "image":
                image = images_by_id.get(block["ref"])
                if not image:
                    continue
                caption = _caption(block, image)
                image_name = f"{image['id']}.jpg"
                shutil.copy(image["path"], images_dir / image_name)
                lines.append(f"![{caption}](images/{image_name})")
                lines.append(f"*{caption}*")
                lines.append("")
            elif block["type"] == "table":
                table = tables_by_id.get(block["ref"])
                if not table:
                    continue
                lines.append(render_table_markdown(table, _caption(block, table)))
                lines.append("")

    output_path = output_dir / "document.md"
    output_path.write_text("\n".join(lines))
    return output_path


FONTS_DIR = Path(__file__).resolve().parent.parent / "assets" / "fonts"

# Same light-mode brand values as the web app (marketing/src/styles/tokens.css).
# Exported documents always use the light palette -- there's no "dark mode"
# for something meant to be printed or handed to someone else.
BRAND = {
    "ink": "#14120f",
    "ink_soft": "#56514a",
    "paper": "#ffffff",
    "paper_shade": "#f2f0ec",
    "line": "#dedbd4",
    "accent": "#c81e3a",
    "accent_ink": "#ffffff",
}


def _hex(color: str) -> str:
    return color.lstrip("#").upper()


def _fit_dimensions(w: int, h: int, max_width_in: float, max_height_in: float) -> tuple[float, float]:
    """Scales to fit within a width AND height cap (not just width), so a
    tall portrait screenshot can't run off the bottom of the page."""
    width_in = max_width_in
    height_in = width_in * (h / w)
    if height_in > max_height_in:
        height_in = max_height_in
        width_in = height_in * (w / h)
    return width_in, height_in


# ---------------------------------------------------------------------------
# DOCX
# ---------------------------------------------------------------------------


def _docx_style_headings(doc) -> None:
    from docx.shared import Pt, RGBColor

    heading1 = doc.styles["Heading 1"]
    heading1.font.name = "Fraunces"
    heading1.font.size = Pt(18)
    heading1.font.bold = True
    heading1.font.color.rgb = RGBColor.from_string(_hex(BRAND["ink"]))
    heading1.paragraph_format.space_before = Pt(18)
    heading1.paragraph_format.space_after = Pt(10)


def _docx_add_cover_page(doc, title: str) -> None:
    from datetime import datetime

    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.shared import Pt, RGBColor

    for _ in range(6):
        doc.add_paragraph()

    title_p = doc.add_paragraph()
    title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title_p.add_run(title)
    title_run.font.name = "Fraunces"
    title_run.font.size = Pt(32)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor.from_string(_hex(BRAND["ink"]))

    subtitle_p = doc.add_paragraph()
    subtitle_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle_run = subtitle_p.add_run(f"Generated by Framewrite · {datetime.now().strftime('%B %d, %Y')}")
    subtitle_run.font.name = "IBM Plex Mono"
    subtitle_run.font.size = Pt(11)
    subtitle_run.italic = True
    subtitle_run.font.color.rgb = RGBColor.from_string(_hex(BRAND["ink_soft"]))

    doc.add_page_break()


def _docx_add_toc(doc) -> None:
    """Inserts a real, clickable TOC field (`{ TOC \\o "1-3" \\h \\z \\u }`) via
    the standard raw-oxml field-code recipe -- python-docx has no high-level
    API for this, but Word auto-populates it from the Heading 1 styles
    already in use once the field is updated (automatically on open, or via
    right-click > Update Field, hence the placeholder text below)."""
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn
    from docx.shared import Pt, RGBColor

    heading_p = doc.add_paragraph()
    heading_run = heading_p.add_run("Contents")
    heading_run.font.name = "Fraunces"
    heading_run.font.size = Pt(16)
    heading_run.font.bold = True
    heading_run.font.color.rgb = RGBColor.from_string(_hex(BRAND["ink"]))

    toc_p = doc.add_paragraph()

    def _field_run(text: str | None = None):
        run = toc_p.add_run(text or "")
        run.font.name = "IBM Plex Mono"
        run.font.size = Pt(10.5)
        return run

    begin = OxmlElement("w:fldChar")
    begin.set(qn("w:fldCharType"), "begin")
    _field_run()._r.append(begin)

    instr = OxmlElement("w:instrText")
    instr.set(qn("xml:space"), "preserve")
    instr.text = 'TOC \\o "1-3" \\h \\z \\u'
    _field_run()._r.append(instr)

    separate = OxmlElement("w:fldChar")
    separate.set(qn("w:fldCharType"), "separate")
    _field_run()._r.append(separate)

    _field_run("Right-click and choose “Update Field” to generate the table of contents.")

    end = OxmlElement("w:fldChar")
    end.set(qn("w:fldCharType"), "end")
    _field_run()._r.append(end)

    doc.add_page_break()


def _docx_add_caption(doc, text: str):
    from docx.shared import Pt, RGBColor

    p = doc.add_paragraph()
    run = p.add_run(text)
    run.italic = True
    run.font.name = "IBM Plex Mono"
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor.from_string(_hex(BRAND["ink_soft"]))
    return p


def _docx_shade_cell(cell, hex_color: str) -> None:
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn

    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_color)
    cell._tc.get_or_add_tcPr().append(shd)


def _docx_set_table_borders(table, hex_color: str) -> None:
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn

    borders = OxmlElement("w:tblBorders")
    for edge in ("top", "left", "bottom", "right", "insideH", "insideV"):
        el = OxmlElement(f"w:{edge}")
        el.set(qn("w:val"), "single")
        el.set(qn("w:sz"), "4")
        el.set(qn("w:color"), hex_color)
        borders.append(el)
    table._tbl.tblPr.append(borders)


def _docx_format_header_row(table, ncols: int) -> None:
    from docx.shared import Pt, RGBColor

    for c in range(ncols):
        cell = table.cell(0, c)
        _docx_shade_cell(cell, _hex(BRAND["ink"]))
        for paragraph in cell.paragraphs:
            for run in paragraph.runs:
                run.font.bold = True
                run.font.name = "IBM Plex Mono"
                run.font.size = Pt(9)
                run.font.color.rgb = RGBColor.from_string(_hex(BRAND["paper"]))


def _docx_add_page_number_field(paragraph) -> None:
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn
    from docx.shared import Pt, RGBColor

    def _run(text: str | None = None):
        run = paragraph.add_run(text or "")
        run.font.name = "IBM Plex Mono"
        run.font.size = Pt(8.5)
        run.font.color.rgb = RGBColor.from_string(_hex(BRAND["ink_soft"]))
        return run

    _run("Page ")

    begin = OxmlElement("w:fldChar")
    begin.set(qn("w:fldCharType"), "begin")
    _run()._r.append(begin)

    instr = OxmlElement("w:instrText")
    instr.set(qn("xml:space"), "preserve")
    instr.text = "PAGE"
    _run()._r.append(instr)

    separate = OxmlElement("w:fldChar")
    separate.set(qn("w:fldCharType"), "separate")
    _run()._r.append(separate)

    _run("1")

    end = OxmlElement("w:fldChar")
    end.set(qn("w:fldCharType"), "end")
    _run()._r.append(end)


def _docx_add_footer(doc) -> None:
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    footer = doc.sections[0].footer
    paragraph = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
    paragraph.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    _docx_add_page_number_field(paragraph)


def _docx_image_dimensions(path: Path, max_width_in: float = 5.5, max_height_in: float = 7.0):
    from docx.shared import Inches

    with PILImage.open(path) as img:
        w, h = img.size
    width_in, height_in = _fit_dimensions(w, h, max_width_in, max_height_in)
    return Inches(width_in), Inches(height_in)


def render_docx(title: str, sections: list[dict], images_by_id: dict, tables_by_id: dict, output_path: Path) -> Path:
    from docx import Document
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()
    _docx_style_headings(doc)
    _docx_add_cover_page(doc, title)

    # A TOC only earns its keep once there's more than one section to jump
    # between -- for a single-section document it would just repeat the one
    # heading already visible on the next page.
    if len(sections) > 1:
        _docx_add_toc(doc)

    for section in sections:
        doc.add_heading(section["heading"], level=1)
        for block in section["blocks"]:
            if block["type"] == "paragraph":
                if block["text"]:
                    doc.add_paragraph(block["text"])
            elif block["type"] == "image":
                image = images_by_id.get(block["ref"])
                if not image:
                    continue
                width, height = _docx_image_dimensions(Path(image["path"]))
                doc.add_picture(image["path"], width=width, height=height)
                doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.CENTER
                caption_p = _docx_add_caption(doc, _caption(block, image))
                caption_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            elif block["type"] == "table":
                table_data = tables_by_id.get(block["ref"])
                if not table_data:
                    continue
                header = [str(h).upper() for h in table_data["headers"]]
                rows = [header] + table_data["rows"]
                table = doc.add_table(rows=len(rows), cols=len(header))
                _docx_set_table_borders(table, _hex(BRAND["line"]))
                for r, row in enumerate(rows):
                    for c, val in enumerate(row):
                        table.cell(r, c).text = str(val)
                _docx_format_header_row(table, len(header))
                _docx_add_caption(doc, _caption(block, table_data))

    _docx_add_footer(doc)
    doc.save(output_path)
    return output_path


# ---------------------------------------------------------------------------
# PDF
# ---------------------------------------------------------------------------

_PDF_FONTS_REGISTERED = False


def _register_pdf_fonts() -> None:
    global _PDF_FONTS_REGISTERED
    if _PDF_FONTS_REGISTERED:
        return
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont

    pdfmetrics.registerFont(TTFont("Fraunces-Bold", str(FONTS_DIR / "fraunces" / "Fraunces-900.ttf")))
    pdfmetrics.registerFont(TTFont("Fraunces-SemiBold", str(FONTS_DIR / "fraunces" / "Fraunces-600.ttf")))
    pdfmetrics.registerFont(TTFont("Fraunces-Italic", str(FONTS_DIR / "fraunces" / "Fraunces-500Italic.ttf")))
    pdfmetrics.registerFont(TTFont("PlexMono", str(FONTS_DIR / "ibm-plex-mono" / "IBMPlexMono-400.ttf")))
    pdfmetrics.registerFont(TTFont("PlexMono-Medium", str(FONTS_DIR / "ibm-plex-mono" / "IBMPlexMono-500.ttf")))
    _PDF_FONTS_REGISTERED = True


def _pdf_styles() -> dict:
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet

    ink = colors.HexColor(BRAND["ink"])
    ink_soft = colors.HexColor(BRAND["ink_soft"])

    body = getSampleStyleSheet()["BodyText"]
    body.textColor = ink
    body.fontSize = 10.5
    body.leading = 15

    return {
        "cover_title": ParagraphStyle(
            "CoverTitle", fontName="Fraunces-Bold", fontSize=34, leading=38, textColor=ink, alignment=TA_CENTER
        ),
        "cover_subtitle": ParagraphStyle(
            "CoverSubtitle",
            fontName="Fraunces-Italic",
            fontSize=13,
            leading=18,
            textColor=ink_soft,
            alignment=TA_CENTER,
            spaceBefore=10,
        ),
        # Name matched against in _ReportDocTemplate.afterFlowable below to
        # decide which paragraphs earn a TOC entry -- keep the two in sync.
        "heading1": ParagraphStyle(
            "SectionHeading", fontName="Fraunces-SemiBold", fontSize=17, leading=21, textColor=ink, spaceBefore=18, spaceAfter=10
        ),
        "body": body,
        "caption": ParagraphStyle("Caption", fontName="PlexMono", fontSize=8.5, leading=12, textColor=ink_soft, spaceAfter=12),
        "toc_heading": ParagraphStyle("TOCHeading", fontName="Fraunces-SemiBold", fontSize=17, leading=21, textColor=ink, spaceAfter=12),
        "toc_entry": ParagraphStyle("TOCEntry", fontName="PlexMono", fontSize=10, leading=16, textColor=ink),
    }


def _pdf_page_furniture(canvas, doc, title: str) -> None:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.units import inch

    canvas.saveState()
    canvas.setStrokeColor(colors.HexColor(BRAND["line"]))
    canvas.setLineWidth(0.75)
    canvas.line(0.75 * inch, 0.65 * inch, letter[0] - 0.75 * inch, 0.65 * inch)

    canvas.setFont("PlexMono", 8.5)
    canvas.setFillColor(colors.HexColor(BRAND["ink_soft"]))
    canvas.drawString(0.75 * inch, 0.45 * inch, title[:60])
    canvas.drawRightString(letter[0] - 0.75 * inch, 0.45 * inch, f"Page {doc.page}")
    canvas.restoreState()


def _build_pdf_doc_template(output_path: Path, title: str):
    from functools import partial

    from reportlab.lib.pagesizes import letter
    from reportlab.lib.units import inch
    from reportlab.platypus import BaseDocTemplate, Frame, PageTemplate, Paragraph

    class _ReportDocTemplate(BaseDocTemplate):
        def afterFlowable(self, flowable):
            # Registers each section heading's resolved page number for the
            # TOC's second build pass, and adds a PDF outline/bookmark entry
            # as a bonus -- a documented reportlab pattern (multiBuild +
            # TOCEntry notifications), not a hack.
            if isinstance(flowable, Paragraph) and flowable.style.name == "SectionHeading":
                text = flowable.getPlainText()
                self.notify("TOCEntry", (0, text, self.page))
                key = f"section-{self.page}-{id(flowable)}"
                self.canv.bookmarkPage(key)
                self.canv.addOutlineEntry(text, key, level=0)

    frame = Frame(0.75 * inch, 0.9 * inch, letter[0] - 1.5 * inch, letter[1] - 1.8 * inch, id="normal")
    template = PageTemplate(id="all", frames=[frame], onPage=partial(_pdf_page_furniture, title=title))
    return _ReportDocTemplate(str(output_path), pagesize=letter, pageTemplates=[template])


def _pdf_image_dimensions(path: Path, max_width_in: float = 4.5, max_height_in: float = 6.0):
    from reportlab.lib.units import inch

    with PILImage.open(path) as img:
        w, h = img.size
    width_in, height_in = _fit_dimensions(w, h, max_width_in, max_height_in)
    return width_in * inch, height_in * inch


def render_pdf(title: str, sections: list[dict], images_by_id: dict, tables_by_id: dict, output_path: Path) -> Path:
    from datetime import datetime

    from reportlab.lib import colors
    from reportlab.platypus import Image as RLImage
    from reportlab.platypus import PageBreak, Paragraph, Spacer, Table, TableStyle
    from reportlab.platypus.tableofcontents import TableOfContents

    _register_pdf_fonts()
    styles = _pdf_styles()
    doc = _build_pdf_doc_template(output_path, title)

    story = [
        Spacer(1, 220),
        Paragraph(escape(title), styles["cover_title"]),
        Paragraph(f"Generated by Framewrite &middot; {datetime.now().strftime('%B %d, %Y')}", styles["cover_subtitle"]),
        PageBreak(),
    ]

    # Same >1-section threshold as the DOCX renderer -- a single-section
    # document doesn't need a table of contents pointing at itself.
    if len(sections) > 1:
        toc = TableOfContents()
        toc.levelStyles = [styles["toc_entry"]]
        story.append(Paragraph("Contents", styles["toc_heading"]))
        story.append(toc)
        story.append(PageBreak())

    for section in sections:
        story.append(Paragraph(escape(section["heading"]), styles["heading1"]))
        for block in section["blocks"]:
            if block["type"] == "paragraph":
                if block["text"]:
                    story.append(Paragraph(escape(block["text"]), styles["body"]))
                    story.append(Spacer(1, 6))
            elif block["type"] == "image":
                image = images_by_id.get(block["ref"])
                if not image:
                    continue
                width, height = _pdf_image_dimensions(Path(image["path"]))
                img = RLImage(image["path"], width=width, height=height)
                img.hAlign = "CENTER"
                story.append(img)
                story.append(Paragraph(escape(_caption(block, image)), styles["caption"]))
            elif block["type"] == "table":
                table_data = tables_by_id.get(block["ref"])
                if not table_data:
                    continue
                header = [str(h).upper() for h in table_data["headers"]]
                rows = [header] + table_data["rows"]
                t = Table(rows)
                t.hAlign = "CENTER"
                t.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(BRAND["ink"])),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor(BRAND["paper"])),
                    ("FONTNAME", (0, 0), (-1, 0), "PlexMono-Medium"),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("TEXTCOLOR", (0, 1), (-1, -1), colors.HexColor(BRAND["ink"])),
                    ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor(BRAND["paper"])),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor(BRAND["line"])),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ]))
                story.append(t)
                story.append(Paragraph(escape(_caption(block, table_data)), styles["caption"]))

    doc.multiBuild(story)
    return output_path
